### PR TITLE
Added privacy policy and terms of service

### PR DESCRIPTION
**Pull request by ghost**
Added pages for each and then created links so they can be accessed from the main page.

### CODE REVIEW

**Comment by ttk2** [comment]
if you could squash this I would be happy to merge.

**Comment by ttk2** [comment]
ok this needs to be against /civcraft/civcraftsite

**Comment by ghost** [comment]
What do you mean? Make a pull request on civcraft/civcraftsite?

**Comment by ttk2** [comment]
yes, this is the wrong repo.

**Comment by ghost** [comment]
I'll submit a pull request to the correct repo first thing tomorrow.

**Pull request closed without merging**
